### ISSUE TITLE
Lack of Data Documentation

### ISSUE THREAD

**Issue by chandrasekarnarayana** [Euro-BioImaging/Data#1]
The data provided in the repo is mentioned as multidimensional sequential data.
They have a width of 232 Px and a height of 253 Px. The Depth is 75 Frames.
The total memory size is 4.2MB.
Bits per Pixel: 8 (Color LUT)

We need the sample or specimen information, fluorescence details, microscope details, the scale of the px and so on...
The experimental/context details and if any publication association with the data.

**Comment by bugraoezdemir** [comment]
Hi @chandrasekarnarayana ,

Thanks for pointing this out. I have updated the repo so that the images are now in the OME-TIFF format, which contains extensive metadata. You can access this metadata by reading the images into ImageJ with the Bio-Formats plugin. For the sake of convenience I have also added an info file with basic metadata here: `FtsZ3_no8/info.md`.

For this dataset, the metadata includes image acquisition and voxel calibration details. No information is available on specimen preparation or regarding any process prior to acquisition. The dataset is not associated with any publication.

**Comment by chandrasekarnarayana** [comment]
Hi @bugraoezdemir,
Thank you for the update.
The addition of [FtsZ3_no8/info.md.](https://github.com/Euro-BioImaging/Data/blob/main/FtsZ3_no8/info.md) will be helpful along with OME_TIFF format.
